name: PR quality gates

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: ESLint & Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test
